name: BlueMapCompass
version: '1.0'
main: fun.mntale.blueMapCompass.BlueMapCompass
api-version: '1.21'
authors: [ MidnightTale_ ]
website: https://mntale.fun
folia-supported: true
dependencies:
  server:
    BlueMap:
      load: BEFORE
      required: true
      join-classpath: true
permissions:
  bluemapcompass.use:
    description: Allows players to use the BlueMap compass GUI
    default: true